package com.example.deploytoazure1.Controller;

import com.example.deploytoazure1.Model.Student;
import com.example.deploytoazure1.Repo.StudentRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

@RestController
@CrossOrigin(value = "*")
public class StudentRestController {

  @Autowired
  StudentRepo studentRepo;

  @GetMapping("/")
  public List<Student> studentsRoot(){
    List<Student> lst = studentRepo.findAll();
    return lst;
  }

  @GetMapping("/students")
  public List<Student> students(){
    List<Student> lst = studentRepo.findAll();
    return lst;
  }

  @GetMapping("/addStudent")
  public List<Student> addStudent(){
    Student std = new Student();
    std.setBorn(LocalDate.now());
    std.setBornTime(LocalTime.now());
    List<Student> lst = studentRepo.findAll();
    std.setName("Autogenerated size =" + lst.size());
    studentRepo.save(std);
    System.out.println("Student save =" + std.getName());
    return lst;
  }

}
